build:
    image: default-jammy
    environment:
        php:
            version: 8.4.12
            ini:
                xdebug.mode: coverage
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - command: pecl install pcov
                    - command: echo "extension=pcov.so" >> ~/.phpenv/versions/8.4.12/etc/php.ini
                    - command: vendor/bin/phpunit --coverage-clover /home/scrutinizer/build/clover.xml
                      coverage: 
                        file: /home/scrutinizer/build/clover.xml
                        format: clover
        tests: true
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
